export const GET_SINGLE_USER_SAGA = 'friends/GET_SINGLE_USER_SAGA';
export const SET_SINGLE_USER = 'friends/SET_SINGLE_USER';
export const GET_ALL_USERS_SAGA = 'friends/GET_ALL_USERS_SAGA';
export const SET_ALL_USERS = 'friends/SET_ALL_USERS';
export const SET_ARE_USERS_LOADING = 'friends/SET_ARE_USERS_LOADING';
export const SET_FRIENDS_STATUS = 'friends/SET_FRIENDS_STATUS';

export const FOLLOW_USER_SAGA = 'friends/FOLLOW_USER_SAGA';

export const REDIRECT_TO_SINGLE_USER_FROM_NOTIFICATIONS = 'friends/REDIRECT_TO_SINGLE_USER_FROM_NOTIFICATIONS';
export const REDIRECT_TO_SINGLE_USER_FROM_FRIENDS_STACK = 'friends/REDIRECT_TO_SINGLE_USER_FROM_FRIENDS_STACK';

export const GET_FRIENDS_SAGA = 'friends/GET_FRIENDS_SAGA';
export const SET_FRIENDS = 'friends/SET_FRIENDS';
export const SET_ARE_FRIENDS_LOADING = 'friends/SET_ARE_FRIENDS_LOADING';
export const SET_IS_FRIEND = 'friends/SET_IS_FRIEND';

export const FRIEND_REQUEST_SAGA = 'friends/FRIEND_REQUEST_SAGA';
export const SYNC_CONTACTS_SAGA = 'friends/SYNC_CONTACTS_SAGA';
export const SET_CONTACTS = 'friends/SET_CONTACTS';
export const FOLLOW_FROM_CONTACTS_SAGA = 'friends/FOLLOW_FROM_CONTACTS_SAGA';
export const SET_FROM_NOTIFICATION = 'friends/SET_FROM_NOTIFICATION';
