export const CHECKOUT_SAGA = 'stripe/CHECKOUT_SAGA';
export const SET_CHECKOUT = 'stripe/SET_CHECKOUT';
export const GET_ACTIVE_SUBSCRIPTION_SAGA = 'stripe/GET_ACTIVE_SUBSCRIPTION_SAGA';
export const SET_ACTIVE_SUBSCRIPTION = 'stripe/SET_ACTIVE_SUBSCRIPTION';
export const CANCEL_SUBSCRIPTION = 'stripe/CANCEL_SUBSCRIPTION';
export const REACTIVATE_SUBSCRIPTION = 'stripe/REACTIVATE_SUBSCRIPTION';
