export const SET_POST_IMAGE = 'profile/SET_POST_IMAGE';
export const NEW_POST_SAGA = 'profile/NEW_POST_SAGA';
export const CREATE_NEW_POST_SAGA = 'profile/CREATE_NEW_POST_SAGA';
export const GET_USER_POSTS_SAGA = 'profile/GET_USER_POSTS_SAGA';
export const SET_USER_POSTS = 'profile/SET_USER_POSTS';
export const SET_USER_POSTS_FROM_CREATE = 'profile/SET_USER_POSTS_FROM_CREATE';
export const SET_ARE_POSTS_LOADING = 'profile/SET_ARE_POSTS_LOADING';

export const GET_SETTINGS_SAGA = 'profile/GET_SETTINGS_SAGA';

export const UPDATE_PROFILE_STATUS_SAGA = 'profile/UPDATE_PROFILE_STATUS_SAGA';
export const UPDATE_PROFILE_THEME_SAGA = 'profile/UPDATE_PROFILE_THEME_SAGA';
export const GET_USER_ACHIEVEMENTS_SAGA = 'profile/GET_USER_ACHIEVEMENTS_SAGA';
export const SET_USER_ACHIEVEMENTS = 'profile/SET_USER_ACHIEVEMENTS';
export const CLOSE_ACHIEVEMENTS_MODAL_SAGA = 'profile/CLOSE_ACHIEVEMENTS_MODAL_SAGA';
export const SHOW_ACHIEVEMENTS_MODAL_SAGA = 'profile/SHOW_ACHIEVEMENTS_MODAL_SAGA';
export const SHOW_ACHIEVEMENTS_CONFETTI = 'profile/SHOW_ACHIEVEMENTS_CONFETTI';
export const SET_ACHIEVEMENT = 'profile/SET_ACHIEVEMENT';

export const FOLLOW_LIST_TYPE = 'profile/FOLLOW_LIST_TYPE';
export const AUTH_USER_FOLLOW_LIST_TYPE = 'profile/AUTH_USER_FOLLOW_LIST_TYPE';
export const GET_FOLLOW_SAGA = 'profile/GET_FOLLOW_SAGA';
export const GET_ALL_FOLLOW_USERS_SAGA = 'profile/GET_ALL_FOLLOW_USERS_SAGA';
export const SET_FOLLOW_USERS = 'profile/SET_FOLLOW_USERS';

export const DELETE_POST_SAGA = 'profile/DELETE_POST_SAGA';
export const REPORT_POST_SAGA = 'profile/REPORT_POST_SAGA';

export const SET_USER_ARRAY = 'profile/SET_USER_ARRAY';
export const REMOVE_FROM_USER_ARRAY_SAGA = 'profile/REMOVE_FROM_USER_ARRAY_SAGA';


export const REDIRECT_TO_FRIEND_PROFILE_SAGA = 'profile/REDIRECT_TO_FRIEND_PROFILE_SAGA';


export const GET_FOLLOWERS_FOLLOWING_SAGA = 'profile/GET_FOLLOWERS_FOLLOWING_SAGA';


